# This is a basic workflow that is manually triggered

name: PortalRestAPIFunctionalTests
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]      
jobs:
  build:
    runs-on: [ self-hosted, ubuntu-latest ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
    - name: Build with Ant
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          echo $GITHUB_TOKEN
